### ISSUE TITLE
incompatibility with facebook pixels

### ISSUE THREAD

**Issue by eshizero** [L3o-pold/prestashopamp#6]
If  facebook pixels and prestashopamp are enabled at the same time.
I have this exception in debug mode:

 UndefinedMethodException

Attempted to call an undefined method named "getTemplateVarProduct" of class "AmpProductModuleFrontController".

After disable "facebook pixel" module all works fine

**Comment by L3o-pold** [comment]
Could you send me the full exception trace?

**Comment by Prestashopnewbie** [comment]
Correct I also use this module for AMP pages. 
Works fine on prestashop 1.7.4.3, but when enable the official facebook pixel module, the server reacts with a 500 error.

**Comment by L3o-pold** [comment]
Did you made an issue on the facebook pixel repository?
Could you send me the full exception trace ?

**Comment by Prestashopnewbie** [comment]
https://imgur.com/a/M9qyxJc
^^ image off the error page, when debug modus is enabled. 

---> I have made an issue on the facebook pixel module to!

**Comment by L3o-pold** [comment]
A quick fix on your side is to disable this module for the AMP pages.

1. Go on the Facebook pixel module settings and click on hooks.
2. Display hidden hooks and edit the Header hook.
3. Add module-amp-category and module-amp-product as exception.

This official Facebook pixel module is not compatible with the AMP technology!

**Comment by L3o-pold** [comment]
I released a new version of the AMP module that will add AMP pages as exception in the Facebook pixel module during the installation.

**Comment by Prestashopnewbie** [comment]
Top works perfect! 

Thanks a lot!

**Comment by sanctusmob** [comment]
The problem still exists in Prestashop 1.7.5.1
If i disable fb pixel is working ok.
I also check the exceptions in header hook and they are there correctly. 

The error i got 

`AH01071: Got error 'PHP message: PHP Fatal error:  Uncaught Error: Call to undefined method AmpProductModuleFrontController::getTemplateVarProduct() in /var/www/vhosts/XXX/httpdocs/modules/pspixel/pspixel.php:233\nStack trace:\n#0 /var/www/vhosts/XXX/httpdocs/classes/Hook.php(966): Pspixel->hookHeader(Array)\n#1 /var/www/vhosts/XXX/httpdocs/classes/Hook.php(355): HookCore::coreCallHook(Object(Pspixel), 'hookHeader', Array)\n#2 /var/www/vhosts/XXX/httpdocs/classes/Hook.php(903): HookCore::callHookOn(Object(Pspixel), 'displayHeader', Array)\n#3 /var/www/vhosts/XXX/httpdocs/classes/controller/FrontController.php(555): HookCore::exec('displayHeader')\n#4 /var/www/vhosts/XXX/httpdocs/classes/controller/ModuleFrontController.php(77): FrontControllerCore->initContent()\n#5 /var/www/vhosts/XXX/httpdocs/modules/amp/controllers/front/product.php(190): ModuleFrontControllerCore->initContent()\n#6 /var/www/vhosts/XXX/httpdocs/classes/controller/Controller.php(281): AmpProdu...\n'
`

**Comment by simobenso** [comment]
Hello, the problem exists even in PS 1.7.6 with Facebook Pixel Officiel v1.1.2.
[pspixel.zip](https://github.com/L3o-pold/prestashopamp/files/3596167/pspixel.zip)

**Comment by L3o-pold** [comment]
I'll have a look this weekend.

**Comment by L3o-pold** [comment]
Fixed in the 2.0.17 release. Please update your module at https://github.com/L3o-pold/prestashopamp/releases/tag/2.0.17

**Comment by simobenso** [comment]
> Fixed in the 2.0.17 release. Please update your module at https://github.com/L3o-pold/prestashopamp/releases/tag/2.0.17

Works like a charm now 👌🏻
